export const SET_MODE = 'SET_MODE'
export const SET_COLLECTION = 'SET_COLLECTION'

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const REMOVE_CARD_FROM_COLLECTION = 'REMOVE_CARD_FROM_COLLECTION'

export const RESET_MODE = 'RESET_MODE'
export const RESET_COLLECTION = 'RESET_COLLECTION'

export const COLLECTION_EDITOR = 'COLLECTION_EDITOR'
export const APPLICATION = 'APPLICATION'